name: Biden Campaign Nostalgia Post (Bluesky)

env:
  DRY_RUN: yes

on: 
#  schedule:
#    - cron:  '46 6,18 * * *'
  
  workflow_dispatch:

jobs:
  post:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Post to Bluesky
      env:
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_BIDEN_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_BIDEN_PASSWORD }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        STATE_DB_GIST: "4caadfb88fedfa23d290122b0937eddc"
        MEMORY_DB_URL: "https://raw.githubusercontent.com/tomcook/nostalgiabot/main/content/biden/memories-campaign.json"
      run: python ./post-bluesky.py

