name: Obama Nostalgia Post (Twitter) (Dry Run)

env:
  DRY_RUN: yes

on: 
  workflow_dispatch:

jobs:
  post:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Post to Twitter
      env:
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_OBAMA_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_OBAMA_ACCESS_TOKEN_SECRET }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_OBAMA_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_OBAMA_CONSUMER_SECRET }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        STATE_DB_GIST: "d34ccb38adf1b9ec9366b892b3e40ae6"
        MEMORY_DB_URL: "https://raw.githubusercontent.com/tomcook/nostalgiabot/main/content/obama/memories.json"
      run: python ./post-twitter.py

